### ISSUE TITLE
Use same or harmonic shades of a color

### ISSUE THREAD

**Issue by martin-at-ipal** [antoinedme/activity-app#1]
Circle uses `#307bbb`
bar graphs use `#3e50b4`

To harmonise multiple shades: https://www.sessions.edu/color-calculator/
1. pick one of the colours,
2. select "Monochromatic Harmony",
3. optionally in `3. see results` "Add More"

**Comment by antoinedme** [comment]
nice one here, 
i'm replacing all colors to harmonize the vizualisation
next commit is gonna correct this
